### ISSUE TITLE
issue：TypeError: write() got an unexpected keyword argument 'fps'

### ISSUE THREAD

**Issue by wanghao19870915** [wangsuzhen/Audio2Head#10]
issue：Traceback (most recent call last):
  File "inference.py", line 251, in <module>
    audio2head(parse.audio_path,parse.img_path,parse.model_path,parse.save_path)
  File "inference.py", line 233, in audio2head
    imageio.mimsave(video_path, predictions_gen,fps=25.0)
  File "D:\miniconda3\envs\a2\lib\site-packages\imageio\v2.py", line 495, in mimwrite
    return file.write(ims, is_batch=True, **kwargs)
  File "D:\miniconda3\envs\a2\lib\site-packages\imageio\plugins\tifffile_v3.py", line 244, in write
    self._fh.write(image, **kwargs)
TypeError: write() got an unexpected keyword argument 'fps'

**Comment by jingli-wtbox** [comment]
Changing the version of imageio can fix the issue.
`pip install imageio==2.5.0`
`pip install imageio-ffmpeg`
