### ISSUE TITLE
RuntimeError: shape '[-1, 1, 4, 41]' is invalid for input of size 186780

### ISSUE THREAD

**Issue by c1a1o1** [wangsuzhen/Audio2Head#6]
RuntimeError: shape '[-1, 1, 4, 41]' is invalid for input of size 186780

**Comment by c1a1o1** [comment]
Input #0, wav, from 'D:/work/vgan/Wav2Lip-master/z930.wav':
  Duration: 00:00:13.88, bitrate: 384 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 24000 Hz, mono, s16, 384 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
-async is forwarded to lavfi similarly to -af aresample=async=1:min_hard_comp=0.100000:first_pts=0.
Output #0, wav, to './results/temp.wav':
  Metadata:
    ISFT            : Lavf58.29.100
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
    Metadata:
      encoder         : Lavc58.54.100 pcm_s16le
size=     434kB time=00:00:13.87 bitrate= 256.0kbits/s speed=4.64e+03x    
video:0kB audio:434kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.017564%
Traceback (most recent call last):
  File "D:/work/vgan/Audio2Head-main/inference.py", line 253, in <module>
    audio2head(parse.audio_path,parse.img_path,parse.model_path,parse.save_path)
  File "D:/work/vgan/Audio2Head-main/inference.py", line 136, in audio2head
    ref_pose_rot, ref_pose_trans = get_pose_from_audio(img, audio_feature, model_path)
  File "D:\work\vgan\Audio2Head-main\modules\audio2pose.py", line 54, in get_pose_from_audio
    poses = generator(x)
  File "D:\anaconda\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\work\vgan\Audio2Head-main\modules\audio2pose.py", line 22, in forward
    audio = x["audio"].reshape(-1, 1, 4, 41)
RuntimeError: shape '[-1, 1, 4, 41]' is invalid for input of size 76120
