### ISSUE TITLE
issuses    TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by flyingree123** [wangsuzhen/Audio2Head#8]
`C:\Users\flyingree\Downloads\Audio2Head-main>python inference.py --audio_path temp.wav --img_path 1.jpg
ffmpeg version 6.0-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, wav, from 'temp.wav':
  Duration: 00:00:10.00, bitrate: 352 kb/s
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 22050 Hz, 1 channels, s16, 352 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to './results/temp.wav':
  Metadata:
    ISFT            : Lavf60.3.100
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
    Metadata:
      encoder         : Lavc60.3.100 pcm_s16le
size=     313kB time=00:00:10.00 bitrate= 256.1kbits/s speed=1.5e+03x
video:0kB audio:313kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.024367%
torch.Size([1, 250, 6])
Traceback (most recent call last):
  File "C:\Users\flyingree\Downloads\Audio2Head-main\inference.py", line 251, in <module>
    audio2head(parse.audio_path,parse.img_path,parse.model_path,parse.save_path)
  File "C:\Users\flyingree\Downloads\Audio2Head-main\inference.py", line 141, in audio2head
    config = yaml.load(f)
TypeError: load() missing 1 required positional argument: 'Loader'`

So what is the matter?

**Comment by flyingree123** [comment]
it is said 'load() missing 1 required positional argument: 'Loader''

**Comment by ahnaf-al** [comment]
I am facing the same issue as well. I

**Comment by HeyIts-RJ** [comment]
I also faced the same issue.

try this:
`!pip install pyyaml==5.4.1`

**Comment by himanshupphp** [comment]
Hello guys, 

instead of 
`load()`

try using
`safe_load`

That will resolve the issue.

**Comment by jingli-wtbox** [comment]
or just pass in 
`Loader=yaml.FullLoader`
