### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './results/temp.wav'

### ISSUE THREAD

**Issue by rongweihe** [wangsuzhen/Audio2Head#9]
mac 环境，直接运行报错

python3 inference.py --audio_path input.wav --img_path input.png
/bin/sh: ffmpeg: command not found
Traceback (most recent call last):
  File "/Users/xxx/Documents/GitHub_Source/Audio2Head/inference.py", line 251, in <module>
    audio2head(parse.audio_path,parse.img_path,parse.model_path,parse.save_path)
  File "/Users/xxx/Documents/GitHub_Source/Audio2Head/inference.py", line 125, in audio2head
    audio_feature = get_audio_feature_from_audio(temp_audio)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Documents/GitHub_Source/Audio2Head/inference.py", line 99, in get_audio_feature_from_audio
    sample_rate, audio = wavfile.read(audio_path)
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/scipy/io/wavfile.py", line 647, in read
    fid = open(filename, 'rb')
          ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './results/temp.wav'

**Comment by RodnoiD1m0n** [comment]
i get it too

**Comment by boycuijg** [comment]
自己创建一个目录results，用于临时存放文件；

**Comment by BowenZhang-github** [comment]
创建了一个目录results，还是报错怎么办？
